INSERT INTO AGENTS(CODENAME, CONTACT, NOTE, STATUS) VALUES ('Bond', 'bondJamesBond@mi6.uk', 'Martini. Shaken, not stirred.', 'ACTIVE');
INSERT INTO AGENTS(CODENAME, CONTACT, NOTE, STATUS) VALUES ('BlackWidow', '459 562 118', 'can speak Russian', 'ACTIVE');

INSERT INTO MISSIONS(MISSIONNAME, LOCATION, STARTTIME, ENDTIME,  DESCRIPTION, STATUS) VALUES ('Cobra', 'Mozambique', '2015-04-16', '2015-05-08', 'remember, no russian', 'WAITING');
INSERT INTO MISSIONS(MISSIONNAME, LOCATION, STARTTIME,  DESCRIPTION, STATUS) VALUES ('Mangus', 'Paris', '2015-02-11', 'will be long', 'ONGOING');
INSERT INTO MISSIONS(MISSIONNAME, LOCATION, STARTTIME, ENDTIME, DESCRIPTION, STATUS) VALUES ('Hydra', 'Zanzibar', '2014-04-16', '2014-05-08', '', 'FINISHED');
INSERT INTO MISSIONS(MISSIONNAME, LOCATION, STARTTIME, ENDTIME,  DESCRIPTION, STATUS) VALUES ('Lama', 'Peru', '2014-02-11', '2014-02-11', '', 'FAILED');